version: "3"

services:
  db:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./docker/:/etc/mysql/conf.d
      - ./docker/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
  php:
    build: ./app
    container_name: php-script-test
    depends_on:
      - "db"
    tty: true
    stdin_open: true
